#pragma once

#define DISPLAY_COLOR_MOD_ACTIVE       0xFF4444
#define DISPLAY_COLOR_MOD_INACTIVE     0x6B2020
#define DISPLAY_COLOR_MOD_SEPARATOR    0x606060
#define DISPLAY_COLOR_MOD_CAPS_WORD    0xffbf00

#define DISPLAY_COLOR_WPM_BAR_ACTIVE   0xE07030
#define DISPLAY_COLOR_WPM_BAR_INACTIVE 0x242424
#define DISPLAY_COLOR_WPM_TEXT         0xE07030

#define DISPLAY_COLOR_LAYER_TEXT       0xffffff
#define DISPLAY_COLOR_LAYER_DOT_ACTIVE   0xe0e0e0
#define DISPLAY_COLOR_LAYER_DOT_INACTIVE 0x575757

#define DISPLAY_COLOR_BATTERY_FILL     0xB4A7D6
#define DISPLAY_COLOR_BATTERY_RING     0x6B5B8A
#define DISPLAY_COLOR_BATTERY_BG       0x505050
#define DISPLAY_COLOR_BATTERY_LABEL    0xffffff

#define DISPLAY_COLOR_BATTERY_DISCONNECTED_FILL  0x383c42
#define DISPLAY_COLOR_BATTERY_DISCONNECTED_RING  0x282c30
#define DISPLAY_COLOR_BATTERY_DISCONNECTED_LABEL 0x000000

#define DISPLAY_COLOR_BATTERY_LOW_FILL  0xC08040
#define DISPLAY_COLOR_BATTERY_LOW_RING  0x584028

#define DISPLAY_COLOR_USB_ACTIVE_BG        0xb9b9a7
#define DISPLAY_COLOR_USB_INACTIVE_BG      0x4F4F40
#define DISPLAY_COLOR_BLE_ACTIVE_BG        0x4A6FA5
#define DISPLAY_COLOR_BLE_INACTIVE_BG      0x2A3A55
#define DISPLAY_COLOR_OUTPUT_ACTIVE_TEXT   0x000000
#define DISPLAY_COLOR_OUTPUT_INACTIVE_TEXT 0x7b7d93

#define DISPLAY_COLOR_SLOT_ACTIVE_BG   0x7b7d93
#define DISPLAY_COLOR_SLOT_INACTIVE_BG 0x353640
#define DISPLAY_COLOR_SLOT_TEXT        0xffffff

#define DISPLAY_COLOR_SLOT_CONNECTED_BG    0x90EE90
#define DISPLAY_COLOR_SLOT_DISCONNECTED_BG 0xF08080
#define DISPLAY_COLOR_SLOT_UNPAIRED_BG     0xFFE680
