#pragma once

#include <stdint.h>

/* Fixed home/white palette for all non-layer-name widgets. */
#define OPERATOR_COLOR_BG     0x0D0D0D
#define OPERATOR_COLOR_DARK   0x3B3B3B
#define OPERATOR_COLOR_MED    0x8F8F8F
#define OPERATOR_COLOR_BRIGHT 0xFFFFFF

#define DISPLAY_COLOR_MOD_ACTIVE         OPERATOR_COLOR_BRIGHT
#define DISPLAY_COLOR_MOD_INACTIVE       OPERATOR_COLOR_DARK
#define DISPLAY_COLOR_MOD_SEPARATOR      OPERATOR_COLOR_DARK
#define DISPLAY_COLOR_MOD_CAPS_WORD      0xCC3333

#define DISPLAY_COLOR_WPM_BAR_ACTIVE     OPERATOR_COLOR_MED
#define DISPLAY_COLOR_WPM_BAR_INACTIVE   OPERATOR_COLOR_BG
#define DISPLAY_COLOR_WPM_TEXT           OPERATOR_COLOR_MED
#define DISPLAY_COLOR_WPM_PEAK           0x6B2020

#define DISPLAY_COLOR_LAYER_TEXT         OPERATOR_COLOR_BRIGHT
#define DISPLAY_COLOR_LAYER_DOT_ACTIVE   OPERATOR_COLOR_MED
#define DISPLAY_COLOR_LAYER_DOT_INACTIVE OPERATOR_COLOR_DARK

#define DISPLAY_COLOR_BATTERY_FILL       OPERATOR_COLOR_MED
#define DISPLAY_COLOR_BATTERY_RING       OPERATOR_COLOR_DARK
#define DISPLAY_COLOR_BATTERY_BG         OPERATOR_COLOR_BG
#define DISPLAY_COLOR_BATTERY_LABEL      OPERATOR_COLOR_MED

#define DISPLAY_COLOR_BATTERY_DISCONNECTED_FILL  0xCC3333
#define DISPLAY_COLOR_BATTERY_DISCONNECTED_RING  0x6B2020
#define DISPLAY_COLOR_BATTERY_DISCONNECTED_LABEL 0xCC3333

#define DISPLAY_COLOR_BATTERY_LOW_FILL   0xCC3333
#define DISPLAY_COLOR_BATTERY_LOW_RING   0x6B2020

#define DISPLAY_COLOR_USB_ACTIVE_BG        0xCC3333
#define DISPLAY_COLOR_USB_INACTIVE_BG      0x6B2020
#define DISPLAY_COLOR_BLE_ACTIVE_BG        OPERATOR_COLOR_MED
#define DISPLAY_COLOR_BLE_INACTIVE_BG      OPERATOR_COLOR_DARK
#define DISPLAY_COLOR_OUTPUT_ACTIVE_TEXT   0x000000
#define DISPLAY_COLOR_OUTPUT_INACTIVE_TEXT OPERATOR_COLOR_DARK

#define DISPLAY_COLOR_SLOT_TEXT            0x000000
#define DISPLAY_COLOR_SLOT_UNPAIRED        0x6B2020
#define DISPLAY_COLOR_SLOT_PAIRED          OPERATOR_COLOR_DARK
#define DISPLAY_COLOR_SLOT_CONNECTED_BG    OPERATOR_COLOR_MED
#define DISPLAY_COLOR_SLOT_DISCONNECTED_BG 0xCC3333
